version: "3.3"
services:
  app:
    container_name: "webapp"
    build: /home/mkoniuszy/IdeaProjects/jjdd2-mojito

    ports:
      - 8801:8080
      - 9900:9990
    depends_on:
      - db
  db:
    container_name: "db"
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=Data
      - MYSQL_USER=mokoniuszy
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
networks:
  Mohito:
    driver: bridge
