version: "3.3"
services:
  app:
    container_name: "webapp"
    build: ../

    ports:
      - 8801:8080
      - 9900:9990
    depends_on:
      - db
  db:
    container_name: "db"
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=STATISTICS
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Infoshare
    ports:
      - 4032:3306
networks:
  Mohito:
    driver: bridge
